configuration:
    type:     rest
    resource: Ecentria\Libraries\EcentriaRestBundle\Controller\ConfigurationController

transaction-service:
    type:     rest
    resource: Ecentria\Libraries\EcentriaRestBundle\Controller\TransactionController
    options:
        expose: true

status:
    type:     rest
    resource: Ecentria\Libraries\EcentriaRestBundle\Controller\StatusController

ping:
    type:     rest
    resource: Ecentria\Libraries\EcentriaRestBundle\Controller\PingController