configuration:
    type:     rest
    resource: Ecentria\Libraries\CoreRestBundle\Controller\ConfigurationController

transaction-service:
    type:     rest
    resource: Ecentria\Libraries\CoreRestBundle\Controller\TransactionController
    options:
        expose: true

status:
    type:     rest
    resource: Ecentria\Libraries\CoreRestBundle\Controller\StatusController

ping:
    type:     rest
    resource: Ecentria\Libraries\CoreRestBundle\Controller\PingController