transaction-service:
    type:     rest
    resource: Ecentria\Libraries\CoreRestBundle\Controller\TransactionController

status:
    type:     rest
    resource: Ecentria\Libraries\CoreRestBundle\Controller\StatusController

ping:
    type:     rest
    resource: Ecentria\Libraries\CoreRestBundle\Controller\PingController