parameters:
    ecentria_libraries_core_rest.object_handler_chain.class: Ecentria\Libraries\CoreRestBundle\HAL\ObjectHandlerChain

services:
    ecentria_libraries_core_rest.object_handler_chain:
        class: %ecentria_libraries_core_rest.object_handler_chain.class%