parameters:
#    ecentria_libraries_core_rest.example.class: Ecentria\Libraries\CoreRestBundle\Example

services:
#    ecentria_libraries_core_rest.example:
#        class: %ecentria_libraries_core_rest.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
