# Converters
services:
    ecentria.doctrine_param_converter:
        arguments:
            - @doctrine
        class: Ecentria\Libraries\CoreRestBundle\Converter\DoctrineParamConverter
        tags:
            - { name: request.param_converter, priority: false, converter: ecentria.doctrine_param_converter }
    ecentria.json_converter:
        class: Ecentria\Libraries\CoreRestBundle\Converter\JsonConverter
        tags:
            - { name: request.param_converter, priority: false, converter: ecentria.json_converter }

    ecentria.array_collection_converter:
        arguments:
            - @doctrine.orm.entity_manager
        class: Ecentria\Libraries\CoreRestBundle\Converter\ArrayCollectionConverter
        tags:
            - { name: request.param_converter, priority: false, converter: ecentria.array_collection_converter }