parameters:

    ecentria.api.converter.array_collection.class: Ecentria\Libraries\CoreRestBundle\Converter\ArrayCollectionConverter
    ecentria.api.converter.json.class:             Ecentria\Libraries\CoreRestBundle\Converter\JsonConverter
    ecentria.api.converter.parameter.class:        Ecentria\Libraries\CoreRestBundle\Converter\ParameterConverter
    ecentria.api.converter.entity.class:           Ecentria\Libraries\CoreRestBundle\Converter\EntityConverter

services:

    ecentria.api.converter.array_collection:
        class: %ecentria.api.converter.array_collection.class%
        arguments:
            - @ecentria.api.crud.transformer
        tags:
            - { name: request.param_converter, priority: false, converter: ecentria.api.converter.array_collection }

    ecentria.api.converter.json:
        class: %ecentria.api.converter.json.class%
        tags:
            - { name: request.param_converter, priority: false, converter: ecentria.api.converter.json }

    ecentria.api.converter.parameter:
        class: %ecentria.api.converter.parameter.class%
        arguments:
            - @doctrine
        tags:
            - { name: request.param_converter, priority: false, converter: ecentria.api.converter.parameter }

    ecentria.api.converter.entity:
        class: %ecentria.api.converter.entity.class%
        arguments:
            - @doctrine
        tags:
            - { name: request.param_converter, priority: false, converter: ecentria.api.converter.entity }