parameters:
    gedmo.listener.timestampable.class: Gedmo\Timestampable\TimestampableListener
    ecentria.controller.transactional_action_listener.class: Ecentria\Libraries\CoreRestBundle\EventListener\TransactionalActionListener

services:
    gedmo.listener.timestampable:
        class: %gedmo.listener.timestampable.class%
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ @annotation_reader ] ]

    ecentria.controller.transactional_action_listener:
        class: %ecentria.controller.transactional_action_listener.class%
        tags:
            - { name: kernel.event_subscriber }
        arguments:
            - @annotation_reader
            - @ecentria.transaction.builder