parameters:
    gedmo.listener.timestampable.class: Gedmo\Timestampable\TimestampableListener

services:
    gedmo.listener.timestampable:
        class: %gedmo.listener.timestampable.class%
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ @annotation_reader ] ]