parameters:
    gedmo.listener.timestampable.class: Gedmo\Timestampable\TimestampableListener
    ecentria.controller.transactional_listener.class: Ecentria\Libraries\CoreRestBundle\EventListener\TransactionalListener
    ecentria.kernel.listener.exception.class: Ecentria\Libraries\CoreRestBundle\EventListener\ExceptionListener

services:
    gedmo.listener.timestampable:
        class: %gedmo.listener.timestampable.class%
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ @annotation_reader ] ]

    ecentria.controller.transactional_listener:
        class: %ecentria.controller.transactional_listener.class%
        tags:
            - { name: kernel.event_subscriber }
        arguments:
            - @annotation_reader
            - @ecentria.transaction.builder
            - @doctrine.orm.default_entity_manager

    ecentria.kernel.listener.exception:
        arguments:
            - @ecentria.transaction_response_manager
        class: %ecentria.kernel.listener.exception.class%
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

    ecentria.response.embedded.listener:
        class: Ecentria\Libraries\CoreRestBundle\EventListener\EmbeddedResponseListener
        tags:
            - { name: kernel.event_listener, event: kernel.view, method: onKernelView, priority: 200 }