parameters:
    ecentria.crud.manager.class: Ecentria\Libraries\CoreRestBundle\Services\CRUDManager
    ecentria.error.response.handler.class: Ecentria\Libraries\CoreRestBundle\Services\ErrorResponseHandler

services:
    ecentria.crud.manager:
        class: %ecentria.crud.manager.class%
        arguments:
            - @doctrine.orm.default_entity_manager
            - @ecentria.entity.validator
            - @event_dispatcher

    ecentria.error.response.handler:
        class: %ecentria.error.response.handler.class%