# Managers
services:
    ecentria.crud.manager:
        class: Ecentria\Libraries\CoreRestBundle\Services\CRUDManager
        arguments:
            - @doctrine.orm.default_entity_manager
            - @ecentria.entity.validator
            - @event_dispatcher

    ecentria.error.response.handler:
        class: Ecentria\Libraries\CoreRestBundle\Services\ErrorResponseHandler