parameters:
    ecentria.crud.transformer.class: Ecentria\Libraries\CoreRestBundle\Services\CRUDTransformer
    ecentria.crud.manager.class: Ecentria\Libraries\CoreRestBundle\Services\CRUDManager
    ecentria.error.response.handler.class: Ecentria\Libraries\CoreRestBundle\Services\ErrorResponseHandler
    ecentria.transaction.builder.class: Ecentria\Libraries\CoreRestBundle\Services\TransactionBuilder
    ecentria.transaction.handler.class: Ecentria\Libraries\CoreRestBundle\Services\TransactionHandler

services:

    ecentria.crud.transformer:
        class: %ecentria.crud.transformer.class%
        arguments:
            - @doctrine.orm.default_entity_manager
            - @annotations.reader

    ecentria.crud.manager:
        class: %ecentria.crud.manager.class%
        arguments:
            - @doctrine.orm.default_entity_manager
            - @ecentria.entity.validator
            - @event_dispatcher
            - @ecentria.crud.transformer

    ecentria.error.response.handler:
        class: %ecentria.error.response.handler.class%

    ecentria.transaction.handler:
        class: %ecentria.transaction.handler.class%
        arguments:
            - @doctrine.orm.default_entity_manager

    ecentria.transaction.builder:
        class: %ecentria.transaction.builder.class%