parameters:

    ecentria.crud.transformer.class: Ecentria\Libraries\CoreRestBundle\Services\CRUD\CRUDTransformer
    ecentria.crud.manager.class: Ecentria\Libraries\CoreRestBundle\Services\CRUD\CRUDManager

    ecentria.error.builder.class: Ecentria\Libraries\CoreRestBundle\Services\ErrorBuilder
    ecentria.notice.builder.class: Ecentria\Libraries\CoreRestBundle\Services\NoticeBuilder

    ecentria.transaction.builder.class: Ecentria\Libraries\CoreRestBundle\Services\Transaction\TransactionBuilder
    ecentria.transaction_response_manager.class: Ecentria\Libraries\CoreRestBundle\Services\Transaction\TransactionResponseManager

    ecentria.transaction_get_handler.class: Ecentria\Libraries\CoreRestBundle\Services\Transaction\Handler\TransactionGetHandler
    ecentria.transaction_patch_handler.class: Ecentria\Libraries\CoreRestBundle\Services\Transaction\Handler\TransactionPatchHandler
    ecentria.transaction_post_handler.class: Ecentria\Libraries\CoreRestBundle\Services\Transaction\Handler\TransactionPostHandler

services:

    ecentria.crud.transformer:
        class: %ecentria.crud.transformer.class%
        arguments:
            - @doctrine.orm.default_entity_manager
            - @annotations.reader

    ecentria.crud.manager:
        class: %ecentria.crud.manager.class%
        arguments:
            - @doctrine.orm.default_entity_manager
            - @ecentria.entity.validator
            - @event_dispatcher
            - @ecentria.crud.transformer

    ecentria.notice.builder:
        class: %ecentria.notice.builder.class%

    ecentria.error.builder:
        class: %ecentria.error.builder.class%

    ecentria.transaction.builder:
        class: %ecentria.transaction.builder.class%

    ecentria.transaction_response_manager:
        class: %ecentria.transaction_response_manager.class%
        arguments: [~]

    ecentria.transaction_get_handler:
        class: %ecentria.transaction_get_handler.class%
        arguments:
            - @doctrine.orm.default_entity_manager
            - @ecentria.error.builder
        tags:
            - { name: ecentria.transaction_method_handler }

    ecentria.transaction_patch_handler:
        class: %ecentria.transaction_patch_handler.class%
        arguments:
            - @ecentria.error.builder
        tags:
            - { name: ecentria.transaction_method_handler }

    ecentria.transaction_post_handler:
        class: %ecentria.transaction_post_handler.class%
        arguments:
            - @doctrine.orm.default_entity_manager
            - @ecentria.error.builder
            - @ecentria.notice.builder
        tags:
            - { name: ecentria.transaction_method_handler }