parameters:

    ecentria.fos_rest.native_json_encode_serializer.class: Ecentria\Libraries\CoreRestBundle\Services\NativeJsonEncodeSerializer

services:

    ecentria.fos_rest.native_json_encode_serializer:
        class: %ecentria.fos_rest.native_json_encode_serializer.class%
