parameters:

    ecentria.api.constraint.circular_reference.class: Ecentria\Libraries\CoreRestBundle\Validator\Constraints\CircularReferenceValidator
    ecentria.api.constraint.email.class:              Ecentria\Libraries\CoreRestBundle\Validator\Constraints\EmailValidator
    ecentria.api.constraint.in_array.class:           Ecentria\Libraries\CoreRestBundle\Validator\Constraints\InArrayValidator
    ecentria.api.constraint.unique_entity.class:      Ecentria\Libraries\CoreRestBundle\Validator\Constraints\UniqueEntityValidator

    ecentria.api.validator.class:                     Symfony\Component\Validator\Validator\RecursiveValidator

services:

    # Constraints
    ecentria.api.constraint.circular_reference:
        class: %ecentria.api.constraint.circular_reference.class%
        tags:
            - { name: validator.constraint_validator, alias: circular_reference }
        calls:
            - [ setEntityManager, [ @doctrine.orm.default_entity_manager ] ]

    ecentria.api.constraint.email:
        class: %ecentria.api.constraint.email.class%
        tags:
            - { name: validator.constraint_validator, alias: email }

    ecentria.api.constraint.in_array:
        class: %ecentria.api.constraint.in_array.class%
        tags:
            - { name: validator.constraint_validator, alias: in_array }

    ecentria.api.constraint.unique_entity:
        class: %ecentria.api.constraint.unique_entity.class%
        arguments:
            - @doctrine
        tags:
            - { name: validator.constraint_validator, alias: unique_entity }
        calls:
            - [ setEntityManager, [ @doctrine.orm.default_entity_manager ] ]

    # Validators
    ecentria.api.validator:
        class: %ecentria.api.validator.class%
        factory_service: validator.builder
        factory_method: getValidator