parameters:
    ecentria.entity.validator.class: Symfony\Component\Validator\Validator\RecursiveValidator
    ecentria.validator.constraints.circular_reference.class: Ecentria\Libraries\CoreRestBundle\Validator\Constraints\CircularReferenceValidator
    ecentria.validator.constraints.in_array.class: Ecentria\Libraries\CoreRestBundle\Validator\Constraints\InArrayValidator
    ecentria.validator.constraints.email.class: Ecentria\Libraries\CoreRestBundle\Validator\Constraints\EmailValidator
    ecentria.validator.constraints.unique_entity.class: Ecentria\Libraries\CoreRestBundle\Validator\Constraints\UniqueEntityValidator

services:
    ecentria.entity.validator:
        class: %ecentria.entity.validator.class%
        factory_service: validator.builder
        factory_method: getValidator

    # Constraints
    ecentria.validator.constraints.circular_reference:
        class: %ecentria.validator.constraints.circular_reference.class%
        tags:
            - { name: validator.constraint_validator, alias: circular_reference }
        calls:
            - [ setEntityManager, [ @doctrine.orm.default_entity_manager ] ]

    ecentria.validator.constraints.in_array:
        class: %ecentria.validator.constraints.in_array.class%
        tags:
            - { name: validator.constraint_validator, alias: in_array }

    ecentria.validator.constraints.email:
        class: %ecentria.validator.constraints.email.class%
        tags:
            - { name: validator.constraint_validator, alias: email }

    ecentria.validator.constraints.unique_entity:
        class: %ecentria.validator.constraints.unique_entity.class%
        arguments:
            - @doctrine
        tags:
            - { name: validator.constraint_validator, alias: unique_entity }
        calls:
            - [ setEntityManager, [ @doctrine.orm.default_entity_manager ] ]