language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

env:
  - SYMFONY_VERSION=2.3.*
  - SYMFONY_VERSION=2.4.*
  - SYMFONY_VERSION=2.5.*
  - SYMFONY_VERSION=2.6.*
  - SYMFONY_VERSION=dev-master

before_script:
  - composer self-update
  - composer require symfony/framework-bundle:${SYMFONY_VERSION} --no-update
  - composer update

script:
  - phpunit --coverage-clover=coverage.clover

notifications:
  email:
    - software@opticsplanet.com

matrix:
  allow_failures:
    - env: SYMFONY_VERSION=dev-master
    - php: hhvm