Ecentria\Libraries\EcentriaRestBundle\Entity\AbstractCrudEntity:

    properties:

        transaction:
            exclude: true

    relations:

        - rel: service-transaction
          exclusion:
              exclude_if: expr(object.getTransaction() === null)
          href:
              route: get_transaction
              parameters:
                  id: expr(object.getTransaction().getId())
              absolute: true
          embedded:
             content: expr(object.getTransaction())
             exclusion:
                groups:
                    - embedded.all
                    - embedded.violation.entity

        - rel: self
          exclusion:
              exclude_if: expr(object.getTransaction() === null || !object.getIds())
          href:
              route: expr(object.getTransaction().getRelatedRoute())
              parameters: expr(object.getIds())
              absolute: true