Ecentria\Libraries\CoreRestBundle\Model\CollectionResponse:

    properties:
        showAssociations:
            exclude: true
        transaction:
            exclude: true

    relations:

        - rel: service-transaction
          exclusion:
              exclude_if: expr(object.getTransaction() === null || !object.showAssociations())
          href:
              route: get_transaction
              parameters:
                  id: expr(object.getTransaction().getId())
              absolute: true
          embedded:
              content: expr(object.getTransaction())